name: Deploy Remote

on:
  workflow_dispatch:
    inputs:
      host:
        type: string
        required: true
      username:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Copy docker-compose.yml to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ github.event.inputs.host }}
        username: ${{ github.event.inputs.username }}
        key: ${{ secrets.SSH_KEY }}
        source: "docker-compose.yml"
        target: "~"

    - name: Deploy with docker-compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ github.event.inputs.host }}
        username: ${{ github.event.inputs.username }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~
          docker-compose pull && docker-compose up -d