name: Publish Remote

on:
  push:
    tags:
      - remote_*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variables
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/remote_*/}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: goldsmithsmocap/remote-streamer:${{ env.RELEASE_VERSION }},goldsmithsmocap/remote-streamer:latest