name: Publish Remote

on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: goldsmithsmocap/remote-streamer:${{ github.event.inputs.release_version }},goldsmithsmocap/remote-streamer:latest